### PR TITLE
DEMO 76 - (FrontEnd) 22: Premium Register Page

### PR DESCRIPTION
**Pull request by karnjj**

### CODE REVIEW

**Comment by karnjj** [comment]
image

**Comment by karnjj** [comment]
image

**Comment by karnjj** [comment]
image

**Review by sseerrnn — APPROVED** [review]
LGTM

**Comment by sseerrnn** [comment]
> 

image
button should be 'upgrade'?

**Review by NonKhuna — APPROVED** [review]
LVGTM

**Comment by karnjj** [comment]
> > 
> 
> image
> button should be 'upgrade' like in UI?

Oh my bad

**Pull request merged**
