### PR TITLE
DEMO 33 - 5: RegisterForm

### PR DESCRIPTION
**Pull request by karnjj**
**Should know**
- replace button component with own shared component.

### CODE REVIEW

**Comment by karnjj** [comment]
image
image

**Review by NonKhuna — APPROVED** [review]
The preview UI is same as Figma design.

**Comment by karnjj** [comment]
> image
> 
> should we use at least 5 character password like in requirement?

Ok I will fix it.

**Comment by karnjj** [comment]
> > image
> > should we use at least 5 character password like in requirement?
> 
> Ok I will fix it.

Fixed

**Pull request closed without merging**
