### PR TITLE
DEMO 69 - (FrontEnd) 19: Playlists/[name] page, playlist title

### PR DESCRIPTION
**Pull request by karnjj**

### CODE REVIEW

**Comment by NonKhuna** [comment]
How can I see the preview page?

**Comment by karnjj** [comment]
image
@NonKhuna sorry kub

**Comment by karnjj** [comment]
> How can I see the preview page?

you can see in URL `{host}/playlists/1`

**Comment by NonKhuna** [comment]
> /playlists/1



> image @NonKhuna sorry kub

I can't see any music items on the table. Is something wrong?

**Pull request merged**
